# Name of my workflow
name: Devops Website

# Controls when the action will run.
# We'll trigger it on a push to the 'main' branch.
on:
  push:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job is named "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN the permissions it needs to deploy to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Step 1: Check out your repository code so the workflow can access it
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Configure GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Step 3: "Build" your site by creating an artifact
      # For a static site, this just means packaging all the files.
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload the root directory of your repository
          path: "."

      # Step 4: Deploy the artifact to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
